services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: emailbreach
        
  reverse-proxy:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    image: reverseproxy
    ports:
      - "80:80"
    depends_on:
      - backend

  backend-arm32:
      platform: linux/arm/v7  
      build:
        context: .
        dockerfile: ./Dockerfile
      image: emailbreach-arm32
        
  reverse-proxy-arm32:
    platform: linux/arm/v7                 
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    image: reverseproxy-arm32
    ports:
      - "80:80"
    depends_on:
      - backend-arm32
