name: ARM32 Reverse Proxy Image Creation

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ajprogramming123
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build ARM32 reverse proxy with Compose
        run: docker compose build backend-arm32 reverse-proxy-arm32

      - name: Tag reverse proxy image for GHCR
        run: docker tag reverse-proxy-arm32 ghcr.io/ajprogramming123/portfolio-reverseproxy-arm32:latest

      - name: Push tagged reverse proxy image to GHCR
        run: docker push ghcr.io/ajprogramming123/portfolio-reverseproxy-arm32:latest
