name: ARM32 Image creation

on:
  workflow_dispatch:
    inputs:
      new_version:
        description: 'New image tag to apply (e.g., v1.2)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ajprogramming123
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build images with docker-compose
        run: docker compose build backend-arm32

      - name: Tag backend-arm32 image for GHCR
        run: docker tag emailbreach-arm32 ghcr.io/ajprogramming123/emailbreach-arm32:${{ github.event.inputs.new_version }}

      - name: Push tagged ARM32 backend image to GHCR
        run: docker push ghcr.io/ajprogramming123/emailbreach-arm32:${{ github.event.inputs.new_version }}
