name: Docker image push!! [flask app setup]

on:
  workflow_dispatch:
    inputs:
      new_version:
        description: 'New image tag to apply (e.g., v1.2)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ajprogramming123
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build images with docker-compose
        run: |
          docker compose build backend


      
      - name: Retag backend image
        run: |
         docker tag emailbreach ghcr.io/ajprogramming123/emailbreach:${{ github.event.inputs.new_version }}
         
      - name: Push new backend tag
        run: docker push ghcr.io/ajprogramming123/emailbreach:${{ github.event.inputs.new_version }}
