name: image push [nginx changes setup] 

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ajprogramming123
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build images with docker-compose
        run: |
          docker compose build

      - name: Push new nginx (reverse proxy) tag
        run: |
          docker tag reverseproxy ghcr.io/ajprogramming123/emailbreach-reverseproxy:latest
          docker push ghcr.io/ajprogramming123/emailbreach-reverseproxy:latest
